# Generated by Django 2.1.2 on 2018-10-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginReg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='apt',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
