# Generated by Django 2.1.2 on 2018-10-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookRev', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
